version: "3"
services:
   datanode:
      image: flokkr/hadoop:katacoda
      command: ["ozone", "datanode"]
      ports:
        - 9864
      env_file:
         - ./config
   ksm:
      image: flokkr/hadoop:katacoda
      hostname: ksm
      command: ["ozone","ksm"]
      ports:
         - 9874:9874
      env_file:
          - ./config
      environment:
         SLEEP_SECONDS: 10
         ENSURE_OM_INITIALIZED: /data/metadata/ozoneManager/current/VERSION
   scm:
      hostname: scm
      image: flokkr/hadoop:katacoda
      command: ["ozone","scm"]
      ports:
         - 9876:9876
      env_file:
          - ./config
      environment:
         ENSURE_SCM_INITIALIZED: /data/metadata/scm/current/VERSION
